secrets = {
    "TELEGRAM_TOKEN": "TELEGRAM_API_TOKEN",
    "TWITTER_CONSUMER_API": "CONSUMER_API",
    "TWITTER_CONSUMER_SECRET": "CONSUMER_SECRET",
    "TWITTER_ACCESS_TOKEN": "ACCESS_TOKEN",
    "TWITTER_ACCESS_SECRET": "ACCESS_SECRET",
}
