secrets = {
    "TELEGRAM_TOKEN": "724630968:AAG3-J26jID34AK_SJg5nJCgr7atiVOZc6A",
    "TWITTER_CONSUMER_API": "CONSUMER_API",
    "TWITTER_CONSUMER_SECRET": "CONSUMER_SECRET",
    "TWITTER_ACCESS_TOKEN": "ACCESS_TOKEN",
    "TWITTER_ACCESS_SECRET": "ACCESS_SECRET",
}
